# Generated by Django 4.2.1 on 2023-06-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sinppet',
            new_name='Snippet',
        ),
    ]
