# Generated by Django 4.2.2 on 2023-06-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contet',
            new_name='content',
        ),
    ]
